import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import express from 'express';
import { chromium } from 'playwright';
import { pool } from './src/db.js';
import { getRoot, readPathForPrincipal, writeValue } from './src/store.js';
import { safeEmailKey } from './src/util.js';
import { registerTariffRoutes, validateZone, tariffRevision } from './src/tarifas.js';

assert.equal(process.env.GOHOUSE_TEST_ONLY, '1', 'Disposable test flag is mandatory');
assert.match(process.env.DATABASE_URL || '', /127\.0\.0\.1.*gohouse_tarifas_test/, 'Never connect this test to production');
const root = process.env.GOHOUSE_SOURCE_ROOT;
const payload = path.join(root,'release/payload/tarifas-2');
const fixtures = path.join(root,'tests/tarifas/fixtures');
const reports = path.join(root,'tests/tarifas/results'); await fs.mkdir(reports,{recursive:true});
const principals = {
 'admin-test': {type:'panel',email:'admin@example.invalid',uid:'admin-test'},
 'operator-test': {type:'panel',email:'operator@example.invalid',uid:'operator-test'},
 'disabled-test': {type:'panel',email:'disabled@example.invalid',uid:'disabled-test'},
 'client-test': {type:'client',uid:'client-test',account:true},
 'driver-test': {type:'driver',uid:'driver-test',driverId:'driver-test'},
 'guest-test': {type:'driver_guest',uid:'guest-test'}
};
const admin=principals['admin-test'], client=principals['client-test'], driver=principals['driver-test'];
const profile={nombre:'Cliente de prueba',celular:'3000000000',cedula:'DEMO',direccion:'Dirección ficticia',ciudad:'Yarumal'};
const initial={'gohouse-data':{orders:[],repartidores:[{id:'driver-test',nombre:'Domiciliario de prueba',estado:'disponible'}],clientes:{'client-test':profile},config:{porcentajeCasa:17.14,valorSugerido:3500,brandName:'Demo de pruebas',sentinel:'preservar'},usuariosPanel:{[safeEmailKey(admin.email)]:{email:admin.email,rol:'administrador'},[safeEmailKey('operator@example.invalid')]:{email:'operator@example.invalid',rol:'operador'},[safeEmailKey('disabled@example.invalid')]:{email:'disabled@example.invalid',rol:'administrador',activo:false}}},publicidad:[{id:'existing-ad',title:'Conservar'}],chats:{existing:{message:'Conservar'}}};
await pool.query('CREATE TABLE IF NOT EXISTS app_state(id integer PRIMARY KEY, data jsonb NOT NULL, version bigint NOT NULL DEFAULT 1, updated_at timestamptz DEFAULT now()); CREATE TABLE IF NOT EXISTS audit_log(id bigserial PRIMARY KEY, actor_type text, actor_id text, action text, path text, metadata jsonb, created_at timestamptz DEFAULT now())');
await pool.query('INSERT INTO app_state(id,data) VALUES(1,$1)',[JSON.stringify(initial)]);
const migration=await fs.readFile(path.join(payload,'migrations/005_tariff_contract.sql'),'utf8'); await pool.query(migration);
const results=[];
async function test(name,fn){await fn();results.push(name);console.log('PASS',results.length,name);}
const g=async()=> (await getRoot()).data['gohouse-data'];
const app=express();app.use(express.json({limit:'10mb'}));
function authMiddleware(){return (req,res,next)=>{req.principal=principals[String(req.headers.authorization||'').replace(/^Bearer /,'')];if(!req.principal)return res.status(401).json({error:'UNAUTHORIZED'});next();};}
registerTariffRoutes(app,{pool,authMiddleware,broadcast:()=>{}});
app.get('/api/auth/session',authMiddleware(),(req,res)=>res.json({user:req.principal}));
app.get('/api/bootstrap/status',(_req,res)=>res.json({needsAdmin:false}));
app.get('/api/public/config',(_req,res)=>res.json({brandName:'Demo de pruebas',shortName:'Demo',primaryColor:'#E8863A',accentColor:'#34C6C0',successColor:'#5FBF8B'}));
app.post('/api/auth/anonymous',(req,res)=>{const token=req.body?.appKind==='domiciliario'?'guest-test':'client-test';res.json({token,user:principals[token]});});
app.post('/api/auth/driver',(_req,res)=>res.json({token:'driver-test',user:driver}));
app.get('/api/push/public-key',(_req,res)=>res.json({publicKey:null}));
app.get('/api/data',authMiddleware(),async(req,res,next)=>{try{const x=await getRoot();res.json({value:readPathForPrincipal(x.data,req.principal,String(req.query.path||'')),version:x.version});}catch(e){next(e);}});
app.put('/api/data',authMiddleware(),async(req,res,next)=>{try{const out=await writeValue(req.principal,req.body.path,req.body.value,req.body.baseValue);res.json({ok:true,version:out.version});}catch(e){next(e);}});
// Only this disposable harness supplies fixed test identities. Production auth is unchanged.
app.get(['/panel/','/gohouse-panel.html'],async(_req,res)=>{let html=await fs.readFile(path.join(fixtures,'gohouse-panel.html'),'utf8');html=html.replace('</body>','<script src="/gohouse-panel-nav.js"></script></body>');res.type('html').send(html.replace('<head>','<head><base href="/">'));});
app.get('/gohouse-panel-nav.js',async(_req,res)=>res.type('js').send(await fs.readFile(path.join(root,'release/payload/panel-nav-2/web/gohouse-panel-nav.js'),'utf8')));
app.get('/gohouse-vps-adapter.js',async(_req,res)=>res.type('js').send(await fs.readFile(path.join(fixtures,'gohouse-vps-adapter.js'),'utf8')));
app.use(express.static(path.join(payload,'web')));
// Unrelated extensions are excluded from the focused UI test; loader preservation is checked separately.
app.get(/\.js$/,(_req,res)=>res.type('js').send('/* unrelated extension isolated in test */'));
app.use((e,_req,res,_next)=>res.status(e.status||(/^TARIFF_/.test(e.message)?409:500)).json({error:e.message}));
const server=await new Promise(resolve=>{const s=app.listen(4217,'127.0.0.1',()=>resolve(s));});
const base='http://127.0.0.1:4217';
async function api(endpoint,method='GET',body,token='admin-test'){const res=await fetch(base+'/api'+endpoint,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:res.status,body:await res.json()};}
const catalog=async()=> (await api('/tarifas')).body;
async function patchZone(id,values){const c=await catalog();const zone=c.zones.find(z=>z.id===id);return api('/tarifas/'+id,'PATCH',{...zone,...values,revision:c.revision});}
let browser;
try {
  await test('11 referencias y valores exactos; El Chaquiro conserva $1.000',async()=>{const c=await catalog();assert.equal(c.zones.length,11);assert.deepEqual(c.zones.map(z=>z.tarifa),[4000,5000,5000,5000,7000,7000,1000,17000,45000,50000,45000]);});
  await test('Migración repetible sin reiniciar configuración',async()=>{const before=await getRoot();await pool.query(migration);assert.deepEqual((await getRoot()).data,before.data);assert.equal((await getRoot()).version,before.version);});
  await test('Permisos: anónimo, cliente, domiciliario, operador y admin inactivo bloqueados',async()=>{for(const token of ['', 'client-test','driver-test','operator-test','disabled-test']){const out=await api('/tarifas','GET',null,token);assert.equal(out.status,token?403:401);const write=await api('/tarifas','POST',{nombre:'No permitido',tarifa:6000,activa:true,revision:'x'},token);assert.equal(write.status,token?403:401);}});
  await test('Validación estricta de importes y nombres duplicados',async()=>{for(const tarifa of [0,-1,1.5,'5000',null,10000001])assert.throws(()=>validateZone({nombre:'Prueba',tarifa,activa:true},[]),/TARIFF_INVALID_AMOUNT/);const c=await catalog();assert.throws(()=>validateZone({nombre:'el rocio',tarifa:6000,activa:true},c.zones),/TARIFF_DUPLICATE_NAME/);});
  let extra;
  await test('Crear y recuperar desde PostgreSQL; revisión estable después de jsonb',async()=>{const c=await catalog();const out=await api('/tarifas','POST',{nombre:'Zona ficticia QA',tarifa:6500,activa:true,revision:c.revision});assert.equal(out.status,201);extra=out.body.zoneId;const fetched=await catalog();assert.equal(fetched.revision,out.body.revision);assert.equal(fetched.zones.find(z=>z.id===extra).tarifa,6500);assert.equal(tariffRevision(fetched.zones),fetched.revision);});
  await test('Editar nombre, valor y estado; cliente solo recibe activas',async()=>{assert.equal((await patchZone(extra,{nombre:'Zona QA editada',tarifa:7500,activa:false})).status,200);const pub=await api('/public/tarifas','GET',null,'');assert.equal(pub.body.zones.some(z=>z.id===extra),false);});
  await test('Eliminar referencia sin afectar base',async()=>{const c=await catalog();assert.equal((await api('/tarifas/'+extra,'DELETE',{revision:c.revision})).status,200);assert.equal((await catalog()).zones.some(z=>z.id===extra),false);});
  await test('Servicio estándar protegido contra eliminar, desactivar y renombrar',async()=>{const c=await catalog();assert.equal((await api('/tarifas/estandar','DELETE',{revision:c.revision})).status,400);assert.equal((await patchZone('estandar',{activa:false})).status,400);assert.equal((await patchZone('estandar',{nombre:'Otro nombre'})).status,400);assert.equal((await patchZone('estandar',{tarifa:4100})).status,200);assert.equal((await patchZone('estandar',{tarifa:4000})).status,200);});
  await test('Ediciones simultáneas no se pisan',async()=>{const c=await catalog();const out=await Promise.all(['Concurrente A','Concurrente B'].map(nombre=>api('/tarifas','POST',{nombre,tarifa:8000,activa:true,revision:c.revision})));assert.deepEqual(out.map(x=>x.status).sort(),[201,409]);const id=out.find(x=>x.status===201).body.zoneId;await api('/tarifas/'+id,'DELETE',{revision:(await catalog()).revision});});
  await test('Identidad, porcentaje, publicidad y chats conservados; cambios auditados',async()=>{const r=(await getRoot()).data;assert.equal(r['gohouse-data'].config.porcentajeCasa,17.14);assert.equal(r['gohouse-data'].config.sentinel,'preservar');assert.deepEqual(r.publicidad,initial.publicidad);assert.deepEqual(r.chats,initial.chats);assert.ok(Number((await pool.query("SELECT count(*) FROM audit_log WHERE action LIKE 'tarifa_%'")).rows[0].count)>0);});
  await test('Ruta genérica no permite saltar protección del catálogo',async()=>{const before=await g();const next=structuredClone(before);next.config.tarifasZonas=next.config.tarifasZonas.filter(z=>z.id!=='estandar');await assert.rejects(writeValue(admin,'gohouse-data',next,before),/TARIFF_SETTINGS_USE_PANEL/);});
  const newOrder={id:'fixed-order',numero:1,clienteUid:client.uid,cliente:profile.nombre,telefono:profile.celular,pedido:'Pedido ficticio',direccion:'Dirección ficticia',lugar:'Tienda ficticia',estado:'nuevo',repartidorId:null,createdAt:Date.now(),day:new Date().toDateString(),zonaTarifaId:'vallecitos',zonaTarifaNombre:'Vallecitos',tarifa:17000,tarifaFijada:true};
  await test('Pedido ciudadano atraviesa store canónico y fija comisión en servidor',async()=>{const before=await g();await writeValue(client,'gohouse-data',{...before,orders:[newOrder]},before);const order=(await g()).orders.find(o=>o.id===newOrder.id);assert.equal(order.tarifa,17000);assert.equal(order.comisionCasa,2914);assert.equal(order.gananciaDomiciliario,14086);assert.equal(order.porcentajeCasaSnapshot,17.14);});
  await test('Precio manipulado y zona inexistente rechazados',async()=>{const before=await g();for(const changes of [{tarifa:1},{zonaTarifaId:'inexistente'}])await assert.rejects(writeValue(client,'gohouse-data',{...before,orders:[...before.orders,{...newOrder,...changes,id:'tampered-order'}]},before),/TARIFF_QUOTE_CHANGED/);});
  await test('Editar tarifa y comisión no altera pedido anterior',async()=>{await patchZone('vallecitos',{tarifa:19000});const before=await g();await writeValue(admin,'gohouse-data',{...before,config:{...before.config,porcentajeCasa:20}},before);const old=(await g()).orders.find(o=>o.id==='fixed-order');assert.equal(old.tarifa,17000);assert.equal(old.comisionCasa,2914);});
  await test('Domiciliario no puede cambiar importe ni comisión, incluso por API',async()=>{let before=await g();await writeValue(driver,'gohouse-data',{...before,orders:before.orders.map(o=>o.id==='fixed-order'?{...o,repartidorId:driver.driverId,estado:'aceptado'}:o)},before);before=await g();for(const changes of [{tarifa:1},{comisionCasa:0}])await assert.rejects(writeValue(driver,'gohouse-data',{...before,orders:before.orders.map(o=>o.id==='fixed-order'?{...o,...changes}:o)},before),/TARIFF_ORDER_LOCKED/);await writeValue(driver,'gohouse-data',{...before,orders:before.orders.map(o=>o.id==='fixed-order'?{...o,estado:'en_destino'}:o)},before);});
  await test('Pedidos antiguos sin referencia mantienen su flujo anterior',async()=>{const before=await g();await writeValue(admin,'gohouse-data',{...before,orders:[...before.orders,{id:'legacy-order',estado:'camino',cliente:'Legado',day:new Date().toDateString(),tarifa:3500,comisionCasa:600}]},before);assert.equal((await g()).orders.find(o=>o.id==='legacy-order').tarifa,3500);});
  await patchZone('vallecitos',{tarifa:17000});
  browser=await chromium.launch({headless:true,args:['--no-sandbox']});
  async function pageFor(kind){const context=await browser.newContext({viewport:{width:1280,height:950},serviceWorkers:'block'});await context.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1'?route.continue():route.abort());await context.addInitScript(({kind,user,profile})=>{localStorage.setItem('gohouse-vps-token-'+kind,kind==='panel'?'admin-test':'client-test');localStorage.setItem('gohouse-vps-user-'+kind,JSON.stringify(user));localStorage.setItem('gohouse-client-profile',JSON.stringify(profile));},{kind,user:kind==='panel'?admin:client,profile});return context.newPage();}
  const panel=await pageFor('panel');const pageErrors=[];panel.on('pageerror',e=>pageErrors.push(e.message));
  await test('Panel real: referencias dentro de Comisión del servicio y botón permanente',async()=>{await panel.goto(base+'/panel/');await panel.locator('#tab-ajustes').click();await panel.waitForFunction(()=>document.querySelectorAll('.gh-tariff-row').length===11);assert.match(await panel.locator('#gh-zonas-tarifas').evaluate(n=>n.closest('section').querySelector('h2').textContent),/Comisión del servicio/);assert.equal(await panel.locator('#gh-add-tariff').textContent(),'+ Agregar referencia');});
  await test('Navegación repetida conserva un solo editor, sin perder formulario abierto',async()=>{await panel.locator('#gh-add-tariff').click();await panel.locator('#gh-tariff-name').fill('Borrador conservado');await panel.evaluate(()=>renderAjustes());await panel.waitForTimeout(120);assert.equal(await panel.locator('#gh-tariff-name').inputValue(),'Borrador conservado');assert.equal(await panel.locator('#gh-zonas-tarifas').count(),1);await panel.locator('#gh-cancel-tariff').click();for(let i=0;i<3;i++){await panel.locator('#tab-pedidos').click();await panel.locator('#tab-ajustes').click();await panel.waitForTimeout(150);}assert.equal(await panel.locator('#gh-add-tariff').count(),1);});
  await test('Crear, editar, desactivar y eliminar por los controles reales',async()=>{await panel.locator('#gh-add-tariff').click();await panel.locator('#gh-tariff-name').fill('Referencia navegador');await panel.locator('#gh-tariff-value').fill('9000');await panel.locator('#gh-save-tariff').click();await panel.waitForFunction(()=>document.querySelectorAll('.gh-tariff-row').length===12);await panel.getByRole('button',{name:'Editar Referencia navegador',exact:true}).click();await panel.locator('#gh-tariff-value').fill('9500');await panel.locator('#gh-tariff-active').selectOption('false');await panel.locator('#gh-save-tariff').click();await panel.waitForFunction(()=>document.querySelector('#gh-tariff-editor').hidden);assert.equal((await api('/public/tarifas','GET',null,'')).body.zones.some(z=>z.nombre==='Referencia navegador'),false);panel.once('dialog',d=>d.dismiss());await panel.getByRole('button',{name:'Eliminar Referencia navegador',exact:true}).click();assert.equal(await panel.locator('.gh-tariff-row').count(),12);panel.once('dialog',d=>d.accept());await panel.getByRole('button',{name:'Eliminar Referencia navegador',exact:true}).click();await panel.waitForFunction(()=>document.querySelectorAll('.gh-tariff-row').length===11);});
  await test('Formulario de estándar permite editar valor, no nombre ni estado',async()=>{await panel.getByRole('button',{name:'Editar Servicio estándar',exact:true}).click();assert.equal(await panel.locator('#gh-tariff-name').isDisabled(),true);assert.equal(await panel.locator('#gh-tariff-active').isDisabled(),true);assert.equal(await panel.getByRole('button',{name:'Eliminar Servicio estándar',exact:true}).count(),0);await panel.locator('#gh-cancel-tariff').click();});
  await panel.locator('#gh-zonas-tarifas').screenshot({path:path.join(reports,'panel-tarifas-desktop.png')});
  await test('Vista móvil: sin desbordamiento horizontal y botón utilizable',async()=>{await panel.setViewportSize({width:390,height:844});await panel.locator('#gh-add-tariff').scrollIntoViewIfNeeded();const size=await panel.locator('#gh-zonas-tarifas').evaluate(n=>({scroll:n.scrollWidth,width:n.clientWidth}));assert.ok(size.scroll<=size.width+1);await panel.screenshot({path:path.join(reports,'panel-tarifas-mobile.png')});});
  const citizen=await pageFor('client');
  await test('Cliente: estándar $4.000, Yarula $50.000 y tarifa visible antes de enviar',async()=>{await citizen.goto(base+'/gohouse-cliente.html');await citizen.waitForFunction(()=>document.querySelector('#gh-client-zone')?.options.length===11);await citizen.evaluate(p=>{perfil=p;goStep('mandado');},profile);await citizen.waitForTimeout(150);assert.match(await citizen.locator('#gh-client-tariff-price').textContent(),/4\.000/);await citizen.locator('#gh-client-zone').selectOption('yarula');assert.match(await citizen.locator('#gh-client-tariff-price').textContent(),/50\.000/);await citizen.locator('#gh-client-tariff').screenshot({path:path.join(reports,'cliente-tarifa.png')});});
  await test('Tarifa cambiada entre selección y envío exige nueva confirmación',async()=>{await patchZone('yarula',{tarifa:51000});const error=await citizen.evaluate(async()=>{try{await GoHouseTarifas.quote();return null;}catch(e){return e.message;}});assert.equal(error,'TARIFF_QUOTE_CHANGED');assert.match(await citizen.locator('#gh-client-tariff-price').textContent(),/51\.000/);await patchZone('yarula',{tarifa:50000});await citizen.evaluate(()=>GoHouseTarifas.refreshClient());});
  await test('Enviar desde cliente real fija solamente el pedido nuevo seleccionado',async()=>{await citizen.locator('#in-lugar').fill('Tienda de prueba');await citizen.locator('#in-descripcion').fill('Pedido ficticio sin despacho real');await citizen.evaluate(()=>selectDestino('otra'));await citizen.locator('#in-direccion').fill('Dirección de prueba');await citizen.locator('#btn-confirmar').click();await citizen.waitForFunction(()=>document.querySelector('#step-seguimiento')?.classList.contains('active'));const orders=(await g()).orders;const created=orders.find(o=>o.descripcion==='Pedido ficticio sin despacho real');assert.equal(created.zonaTarifaId,'yarula');assert.equal(created.tarifa,50000);assert.equal(created.comisionCasa,10000);assert.equal(orders.find(o=>o.id==='fixed-order').tarifa,17000);});
  const courier=await pageFor('domiciliario');
  await test('Pantalla real domiciliario bloquea tarifa y muestra comisión histórica',async()=>{await courier.goto(base+'/gohouse-domiciliarios.html');await courier.waitForTimeout(200);await courier.evaluate(async()=>{await auth.signInDriver('driver-test','0000');data=(await dbRef.once('value')).val();miId='driver-test';render();});await courier.locator('#in-valor-servicio-salida').waitFor();assert.equal(await courier.locator('#in-valor-servicio-salida').getAttribute('readonly'),'');assert.equal(await courier.locator('#in-valor-servicio-salida').inputValue(),'17000');assert.match(await courier.locator('#preview-ganancia-salida').textContent(),/14\.086/);await courier.locator('#gh-driver-fixed-tariff').screenshot({path:path.join(reports,'domiciliario-tarifa-fijada.png')});});
  await test('Salida y entrega no sobrescriben tarifa ni comisión',async()=>{await courier.locator('#in-valor-compra').fill('25000');await courier.evaluate(()=>marcarEnCamino('fixed-order'));let order=(await g()).orders.find(o=>o.id==='fixed-order');assert.equal(order.estado,'camino');assert.equal(order.tarifa,17000);assert.equal(order.comisionCasa,2914);await courier.evaluate(()=>marcarEntregado('fixed-order'));order=(await g()).orders.find(o=>o.id==='fixed-order');assert.equal(order.estado,'entregado');assert.equal(order.comisionCasa,2914);});
  await test('Módulos existentes de marca blanca, push, publicidad e instalación preservados',async()=>{const branding=await fs.readFile(path.join(payload,'web/gohouse-branding.js'),'utf8');for(const name of ['gohouse-app-shell.js','gohouse-push.js','gohouse-qr.js','gohouse-publicidad.js','gohouse-install.js'])assert.ok(branding.includes(name));assert.equal(pageErrors.length,0,JSON.stringify(pageErrors));});
  console.log('ALL_PASS',results.length);
  await fs.writeFile(path.join(reports,'results.json'),JSON.stringify({ok:true,count:results.length,checks:results},null,2));
} catch(error) {console.error('FAILED_AFTER',results.length,error);await fs.writeFile(path.join(reports,'results.json'),JSON.stringify({ok:false,count:results.length,checks:results,error:String(error)},null,2));process.exitCode=1;}
finally {await browser?.close();await new Promise(resolve=>server.close(resolve));await pool.end();}
